name: flutter_simple_rest_api
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  flutter_secure_storage: ^6.0.0
  flash: ^2.0.5
  auto_route: ^5.0.2
  material_design_icons_flutter: ^5.0.6996
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  equatable: ^2.0.3
  formz: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  freezed: ^2.2.1
  auto_route_generator: ^5.0.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/raleway/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/raleway/Raleway-ExtraLight.ttf
          weight: 200
        - asset: fonts/raleway/Raleway-Light.ttf
          weight: 300
        - asset: fonts/raleway/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/raleway/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/raleway/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/raleway/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/raleway/Raleway-Black.ttf
          weight: 900
